SCM_CVS_VERSION_1_11_x_BIN_PATH="/usr/local/cvs-1.11.21/bin"
SCM_CVS_VERSION_1_12_x_BIN_PATH="/usr/local/cvs-1.12.13/bin"

SCM_SVN_VERSION_1_0_x_BIN_PATH="/usr/local/subversion-1.0.6/bin"
SCM_SVN_VERSION_1_1_x_BIN_PATH="/usr/local/subversion-1.1.3/bin"
SCM_SVN_VERSION_1_2_x_BIN_PATH="/usr/local/subversion-1.2.3/bin"
SCM_SVN_VERSION_1_3_x_BIN_PATH="/usr/local/subversion-1.3.0/bin"
SCM_SVN_VERSION_1_4_x_BIN_PATH="/usr/local/subversion-1.4.5/bin"
SCM_SVN_VERSION_1_5_x_BIN_PATH="/usr/local/subversion-1.5.1/bin"
SCM_SVN_VERSION_1_6_x_BIN_PATH="/usr/local/subversion-1.6.1/bin"

SCM_GIT_VERSION_1_5_x_BIN_PATH="/usr/local/git-1.5.6/bin"

SCM_GENERAL_BIN_PATH="/usr/bin,/bin"
